
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Teste
      MYSQL_USER: R1cky
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
